### ISSUE TITLE
签名验签问题

### ISSUE THREAD

**Issue by hpy777** [songgeng87/SM9_FREE#6]
1、写死随机数，但每次执行签名结果不同
2、将msg改为非Chinese IBS standard，比如 abcd 等等，验签会失败

**Comment by songgeng87** [comment]
博主在外出差，晚上回宾馆看下




            
            
                
                    
                            
                                
                            
                            
                                宋承根
                            
                    
                        
                            
                                    邮箱：songgeng87@gmail.com
                            
                        
                
            
        签名由 网易邮箱大师 定制


在2019年05月27日 17:23，hpy 写道： 1、写死随机数，但每次执行签名结果不同
2、将msg改为非Chinese IBS standard，比如 abcd 等等，验签会失败

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/songgeng87/SM9_FREE/issues/6?email_source=notifications\u0026email_token=ABICRM2MAZFFGZ6GSUMGKWDPXOSBDA5CNFSM4HP2EYS2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GV7OI4Q",
"url": "https://github.com/songgeng87/SM9_FREE/issues/6?email_source=notifications\u0026email_token=ABICRM2MAZFFGZ6GSUMGKWDPXOSBDA5CNFSM4HP2EYS2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GV7OI4Q",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by songgeng87** [comment]
经过我自己的测试，没有出现您说的这两种种情况。

您是否在修改msg以后，没有传入正确的msg长度？

**Comment by hpy777** [comment]
我再试试看 感觉像是这个问题

**Comment by hpy777** [comment]
已解决，感谢博主

**Comment by hpy777** [comment]
已经解决，确实这个问题，感谢
