### ISSUE TITLE
print_big和sm9_init中的epoint_set

### ISSUE THREAD

**Issue by brant98** [songgeng87/SM9_FREE#9]
输出big不正确，只能输出28字节。并且我的SM9_init也不能正确运行。epoint_set始终不对，是怎么回事呢，谢谢博主。

**Comment by songgeng87** [comment]
检查下运行环境～～




    


在2020年08月12日 11:41，brant98 写道： 
输出big不正确，只能输出28字节。并且我的SM9_init也不能正确运行。epoint_set始终不对，是怎么回事呢，谢谢博主。

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/songgeng87/SM9_FREE/issues/9",

"url": "https://github.com/songgeng87/SM9_FREE/issues/9",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by brant98** [comment]
环境没有问题，编译也都通过了的，只是程序没能成功运行。sm9_init就错误了。改了好久没能成功

**Comment by brant98** [comment]
> 检查下运行环境～～ 在2020年08月12日 11:41，brant98 写道： 输出big不正确，只能输出28字节。并且我的SM9_init也不能正确运行。epoint_set始终不对，是怎么回事呢，谢谢博主。 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#9", "url": "#9", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]



> 检查下运行环境～～ 在2020年08月12日 11:41，brant98 写道： 输出big不正确，只能输出28字节。并且我的SM9_init也不能正确运行。epoint_set始终不对，是怎么回事呢，谢谢博主。 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#9", "url": "#9", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

环境没有问题，编译也都通过了的，只是程序没能成功运行。sm9_init就错误了。改了好久没能成功
